# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2
project_name: bureau

builds:
  - id: bureau
    binary: bureau
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

nfpms:
- maintainer: Jake Nabasny <jake@nabasny.com>
  description: Bureau cofiguration sync tool for LDAP
  homepage: https://github.com/slapcat/scribe
  formats:
  - deb
  - rpm
  contents:
    - src: ./systemd/bureau.service
      dst: /usr/lib/systemd/system/bureau.service
    - src: ./bureau.yaml.example
      dst: /etc/bureau/bureau.yaml.example

changelog:
  sort: asc
